repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^libs/

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args: [ "-c", "bandit.yaml" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: codespell
        args: [ '--ignore-words', '.codespell.ignorewords']
        exclude: .venv

  - repo: local
    hooks:
      - id: xenon-complexity
        name: xenon complexity check
        entry: python -m xenon --max-absolute B --max-modules B --max-average B ./src
        language: python
        types: [ python ]
        additional_dependencies: [ xenon ]
        pass_filenames: false
        always_run: true

      - id: mutation-testing
        name: mutation testing
        language: python
        language_version: python3
        additional_dependencies:
          - mutmut==3.3.0
          - pytest==8.3.5
          - pytest-cov==6.2.1
        entry: python scripts/mutmut_check.py --min-score 80
        pass_filenames: false

      - id: coverage_check
        name: pytest coverage check
        language: python
        language_version: python3
        additional_dependencies:
          - pytest==8.3.5
          - pytest-cov==6.0.0
        entry: pytest --cov=src --cov-report=term-missing --cov-report=html --cov-fail-under=80
        types: [ python ]
        pass_filenames: false
        always_run: true
        verbose: true